name: hymet_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - perl
  - mash
  - minimap2
  - mashmap
  - wget
  - pandas
  - numpy
  - pip
  - biopython
  - csvkit
  - trimmomatic
  - bowtie2
  - spades
  - seqtk
  - pip:
      - biopython  